# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.16.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.16.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/justin/Desktop/windingnum/homework

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/justin/Desktop/windingnum/homework

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.16.3/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.16.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.16.3/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/justin/Desktop/windingnum/homework/CMakeFiles /Users/justin/Desktop/windingnum/homework/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/justin/Desktop/windingnum/homework/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named winding_lib

# Build rule for target.
winding_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 winding_lib
.PHONY : winding_lib

# fast build rule for target.
winding_lib/fast:
	$(MAKE) -f CMakeFiles/winding_lib.dir/build.make CMakeFiles/winding_lib.dir/build
.PHONY : winding_lib/fast

#=============================================================================
# Target rules for targets named winding_number_test

# Build rule for target.
winding_number_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 winding_number_test
.PHONY : winding_number_test

# fast build rule for target.
winding_number_test/fast:
	$(MAKE) -f CMakeFiles/winding_number_test.dir/build.make CMakeFiles/winding_number_test.dir/build
.PHONY : winding_number_test/fast

#=============================================================================
# Target rules for targets named winding_number

# Build rule for target.
winding_number: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 winding_number
.PHONY : winding_number

# fast build rule for target.
winding_number/fast:
	$(MAKE) -f CMakeFiles/winding_number.dir/build.make CMakeFiles/winding_number.dir/build
.PHONY : winding_number/fast

googletest/googletest/src/gtest-all.o: googletest/googletest/src/gtest-all.cc.o

.PHONY : googletest/googletest/src/gtest-all.o

# target to build an object file
googletest/googletest/src/gtest-all.cc.o:
	$(MAKE) -f CMakeFiles/winding_number_test.dir/build.make CMakeFiles/winding_number_test.dir/googletest/googletest/src/gtest-all.cc.o
.PHONY : googletest/googletest/src/gtest-all.cc.o

googletest/googletest/src/gtest-all.i: googletest/googletest/src/gtest-all.cc.i

.PHONY : googletest/googletest/src/gtest-all.i

# target to preprocess a source file
googletest/googletest/src/gtest-all.cc.i:
	$(MAKE) -f CMakeFiles/winding_number_test.dir/build.make CMakeFiles/winding_number_test.dir/googletest/googletest/src/gtest-all.cc.i
.PHONY : googletest/googletest/src/gtest-all.cc.i

googletest/googletest/src/gtest-all.s: googletest/googletest/src/gtest-all.cc.s

.PHONY : googletest/googletest/src/gtest-all.s

# target to generate assembly for a file
googletest/googletest/src/gtest-all.cc.s:
	$(MAKE) -f CMakeFiles/winding_number_test.dir/build.make CMakeFiles/winding_number_test.dir/googletest/googletest/src/gtest-all.cc.s
.PHONY : googletest/googletest/src/gtest-all.cc.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/winding_number.dir/build.make CMakeFiles/winding_number.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/winding_number.dir/build.make CMakeFiles/winding_number.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/winding_number.dir/build.make CMakeFiles/winding_number.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/poly_io.o: src/poly_io.cpp.o

.PHONY : src/poly_io.o

# target to build an object file
src/poly_io.cpp.o:
	$(MAKE) -f CMakeFiles/winding_lib.dir/build.make CMakeFiles/winding_lib.dir/src/poly_io.cpp.o
.PHONY : src/poly_io.cpp.o

src/poly_io.i: src/poly_io.cpp.i

.PHONY : src/poly_io.i

# target to preprocess a source file
src/poly_io.cpp.i:
	$(MAKE) -f CMakeFiles/winding_lib.dir/build.make CMakeFiles/winding_lib.dir/src/poly_io.cpp.i
.PHONY : src/poly_io.cpp.i

src/poly_io.s: src/poly_io.cpp.s

.PHONY : src/poly_io.s

# target to generate assembly for a file
src/poly_io.cpp.s:
	$(MAKE) -f CMakeFiles/winding_lib.dir/build.make CMakeFiles/winding_lib.dir/src/poly_io.cpp.s
.PHONY : src/poly_io.cpp.s

src/winding.o: src/winding.cpp.o

.PHONY : src/winding.o

# target to build an object file
src/winding.cpp.o:
	$(MAKE) -f CMakeFiles/winding_lib.dir/build.make CMakeFiles/winding_lib.dir/src/winding.cpp.o
.PHONY : src/winding.cpp.o

src/winding.i: src/winding.cpp.i

.PHONY : src/winding.i

# target to preprocess a source file
src/winding.cpp.i:
	$(MAKE) -f CMakeFiles/winding_lib.dir/build.make CMakeFiles/winding_lib.dir/src/winding.cpp.i
.PHONY : src/winding.cpp.i

src/winding.s: src/winding.cpp.s

.PHONY : src/winding.s

# target to generate assembly for a file
src/winding.cpp.s:
	$(MAKE) -f CMakeFiles/winding_lib.dir/build.make CMakeFiles/winding_lib.dir/src/winding.cpp.s
.PHONY : src/winding.cpp.s

test/poly_io_test.o: test/poly_io_test.cpp.o

.PHONY : test/poly_io_test.o

# target to build an object file
test/poly_io_test.cpp.o:
	$(MAKE) -f CMakeFiles/winding_number_test.dir/build.make CMakeFiles/winding_number_test.dir/test/poly_io_test.cpp.o
.PHONY : test/poly_io_test.cpp.o

test/poly_io_test.i: test/poly_io_test.cpp.i

.PHONY : test/poly_io_test.i

# target to preprocess a source file
test/poly_io_test.cpp.i:
	$(MAKE) -f CMakeFiles/winding_number_test.dir/build.make CMakeFiles/winding_number_test.dir/test/poly_io_test.cpp.i
.PHONY : test/poly_io_test.cpp.i

test/poly_io_test.s: test/poly_io_test.cpp.s

.PHONY : test/poly_io_test.s

# target to generate assembly for a file
test/poly_io_test.cpp.s:
	$(MAKE) -f CMakeFiles/winding_number_test.dir/build.make CMakeFiles/winding_number_test.dir/test/poly_io_test.cpp.s
.PHONY : test/poly_io_test.cpp.s

test/testmain.o: test/testmain.cpp.o

.PHONY : test/testmain.o

# target to build an object file
test/testmain.cpp.o:
	$(MAKE) -f CMakeFiles/winding_number_test.dir/build.make CMakeFiles/winding_number_test.dir/test/testmain.cpp.o
.PHONY : test/testmain.cpp.o

test/testmain.i: test/testmain.cpp.i

.PHONY : test/testmain.i

# target to preprocess a source file
test/testmain.cpp.i:
	$(MAKE) -f CMakeFiles/winding_number_test.dir/build.make CMakeFiles/winding_number_test.dir/test/testmain.cpp.i
.PHONY : test/testmain.cpp.i

test/testmain.s: test/testmain.cpp.s

.PHONY : test/testmain.s

# target to generate assembly for a file
test/testmain.cpp.s:
	$(MAKE) -f CMakeFiles/winding_number_test.dir/build.make CMakeFiles/winding_number_test.dir/test/testmain.cpp.s
.PHONY : test/testmain.cpp.s

test/winding_test.o: test/winding_test.cpp.o

.PHONY : test/winding_test.o

# target to build an object file
test/winding_test.cpp.o:
	$(MAKE) -f CMakeFiles/winding_number_test.dir/build.make CMakeFiles/winding_number_test.dir/test/winding_test.cpp.o
.PHONY : test/winding_test.cpp.o

test/winding_test.i: test/winding_test.cpp.i

.PHONY : test/winding_test.i

# target to preprocess a source file
test/winding_test.cpp.i:
	$(MAKE) -f CMakeFiles/winding_number_test.dir/build.make CMakeFiles/winding_number_test.dir/test/winding_test.cpp.i
.PHONY : test/winding_test.cpp.i

test/winding_test.s: test/winding_test.cpp.s

.PHONY : test/winding_test.s

# target to generate assembly for a file
test/winding_test.cpp.s:
	$(MAKE) -f CMakeFiles/winding_number_test.dir/build.make CMakeFiles/winding_number_test.dir/test/winding_test.cpp.s
.PHONY : test/winding_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... winding_lib"
	@echo "... winding_number_test"
	@echo "... test"
	@echo "... winding_number"
	@echo "... googletest/googletest/src/gtest-all.o"
	@echo "... googletest/googletest/src/gtest-all.i"
	@echo "... googletest/googletest/src/gtest-all.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/poly_io.o"
	@echo "... src/poly_io.i"
	@echo "... src/poly_io.s"
	@echo "... src/winding.o"
	@echo "... src/winding.i"
	@echo "... src/winding.s"
	@echo "... test/poly_io_test.o"
	@echo "... test/poly_io_test.i"
	@echo "... test/poly_io_test.s"
	@echo "... test/testmain.o"
	@echo "... test/testmain.i"
	@echo "... test/testmain.s"
	@echo "... test/winding_test.o"
	@echo "... test/winding_test.i"
	@echo "... test/winding_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

